config/routes.rb
Ticketee::Application.routes.draw do
  root :to => 'projects#index'
  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
	end

	def new
		@project = Project.new
	end

	def create 
		@project = Project.new(params[:project])
		if @project.save
			redirect_to @project,
			:flash => {:success => 'Project has been created.'}
		else
			#nothing
		end
	end

	def show
		@project = Project.find(params[:id])
	end

	def edit
	end

	def update
	end

	def destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketee</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="container">
		<div class="content">
			<div id="main">
				<% flash.each do |key, value| %>
					<div id="<%= key %>"> <%= value %> </div>
				<% end %>
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/projects/index.html.erb
<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= form_for(@project) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_field :description %>
	</p>
	<%= f.submit 'Create Project' %>
<% end %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p><%= @project.description %></p>